CC = cc
NAME = libmy.a

OBJ = 0-isupper.o  100-atoi.o   1-strncat.o  2-strncpy.o  3-strcmp.o   4-strpbrk.o  9-strcpy.o  _putchar.o \
0-memset.o   1-isdigit.o  2-strchr.o   3-islower.o  3-strspn.o   5-strstr.o \
0-strcat.o   1-memcpy.o   2-strlen.o   3-puts.o   4-isalpha.o  6-abs.o 

all: $(NAME)

$(NAME): $(OBJ)
	ar -rc $(NAME) $(OBJ)
